using System.Text;

namespace YtDlpAudio.Infrastructure.Auth;

public record CookieRecord(
    string Domain,
    string Name,
    string Value,
    string Path = "/",
    double? Expires = null,
    bool IsSecure = true,
    bool IsHttpOnly = false
);

public static class NetscapeCookieFormatter
{
    private const string Header = 
        "# Netscape HTTP Cookie File\n" +
        "# http://curl.haxx.se/rfc/cookie_spec.html\n" +
        "# This file was generated by YtDlpAudio. Do not edit.\n\n";

    public static string Format(IEnumerable<CookieRecord> cookies)
    {
        var sb = new StringBuilder();
        sb.Append(Header);

        foreach (var cookie in cookies)
        {
            if (string.IsNullOrWhiteSpace(cookie.Name)) continue;

            string domain = cookie.Domain.Trim();
            bool includeSubdomains = domain.StartsWith(".");
            if (!includeSubdomains && !domain.StartsWith("."))
            {
                // Format convention for Netscape: subdomains allowed should have leading dot
                domain = "." + domain;
                includeSubdomains = true;
            }

            string subdomainsFlag = includeSubdomains ? "TRUE" : "FALSE";
            string path = string.IsNullOrWhiteSpace(cookie.Path) ? "/" : cookie.Path;
            string secureFlag = cookie.IsSecure ? "TRUE" : "FALSE";
            long expiration = cookie.Expires.HasValue && cookie.Expires.Value > 0
                ? (long)cookie.Expires.Value
                : DateTimeOffset.UtcNow.AddYears(1).ToUnixTimeSeconds();

            sb.Append(domain).Append('\t')
              .Append(subdomainsFlag).Append('\t')
              .Append(path).Append('\t')
              .Append(secureFlag).Append('\t')
              .Append(expiration).Append('\t')
              .Append(cookie.Name).Append('\t')
              .Append(cookie.Value).Append('\n');
        }

        return sb.ToString();
    }
}
